# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_year', models.IntegerField(default=2000, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(default='')),
                ('review_date', models.DateTimeField(verbose_name='review date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djbr.Book')),
            ],
        ),
    ]
