# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djbr', '0002_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='review date'),
        ),
    ]
